version: "3"

services:
    firefish:
        build: .
        image: ghcr.io/mizunashi-mana/firefish-dist-pkg/debian-runner
        depends_on:
            - postgres
            - redis
        ports:
            - "3000:3000"
        networks:
            - internal-net
        volumes:
            - ./docker/default.yml:/etc/firefish/default.yml:ro
            - firefish-files:/var/lib/firefish/files

    redis:
        image: docker.io/redis:7.0-alpine
        networks:
            - internal-net
        volumes:
            - redis-data:/data

    postgres:
        image: docker.io/postgres:15-alpine
        networks:
            - internal-net
        env_file:
            - ./docker/postgres.env
        volumes:
            - postgres-data:/var/lib/postgresql/data

networks:
    internal-net:

volumes:
    redis-data:
    postgres-data:
    firefish-files:
