name: Deploy for amd64 / Debian bullseye

on:
    push:
        branches: [ "main" ]
        tags: [ "*" ]
    pull_request:
        branches: [ "main" ]

env:
    DISTRO_BASE: debian
    DISTRO: bullseye

jobs:
    build-deb:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Generate params if needed
                if: startsWith(github.ref, 'refs/tags/')
                run: ./debian/scripts/gen-params

            -   name: Check package version
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    source ./debian/scripts/env.bash
                    [ "$PKG_VERSION" = "$GITHUB_REF_NAME" ]

            -   name: Cache Docker layers
                uses: actions/cache@v3
                with:
                    path: /tmp/.buildx-cache
                    key: buildx-cache-${{ hashFiles('./debian/scripts/env.bash') }}-${{ github.sha }}
                    restore-keys: |
                        buildx-cache-${{ hashFiles('./debian/scripts/env.bash') }}-${{ github.sha }}
                        buildx-cache-${{ hashFiles('./debian/scripts/env.bash') }}-

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
                with:
                    install: true
                    driver-opts: network=host

            -   name: Build deb
                uses: docker/build-push-action@v4
                with:
                    context: ./debian
                    load: true
                    target: debcontainer
                    build-args: |
                        DISTRO_BASE=${{ env.DISTRO_BASE }}
                        DEBIAN_DISTRO=${{ env.DISTRO }}
                    tags: ghcr.io/mizunashi-mana/firefish-dist-pkg/debian-debcontainer
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache

            -   name: Copy deb
                run: |
                    docker create --name deb ghcr.io/mizunashi-mana/firefish-dist-pkg/debian-debcontainer
                    docker cp deb:/workdir/dest ./dest
                    docker rm deb
                    ls ./dest

            -   name: Archive deb artifact
                uses: actions/upload-artifact@v3
                with:
                    name: deb
                    retention-days: 1
                    path: |
                        ./dest/*.deb

            -   name: Pull compose images
                run: |
                    docker compose -f debian/docker-compose.yml pull

            -   name: Build compose images
                uses: docker/bake-action@v3
                with:
                    workdir: ./debian
                    files: ./docker-compose.yml
                    load: true
                    set: |
                        *.cache-from=type=local,src=/tmp/.buildx-cache
                        *.cache-to=type=local,dest=/tmp/.buildx-cache
                        *.args.DISTRO_BASE=${{ env.DISTRO_BASE }}
                        *.args.DISTRO=${{ env.DISTRO }}

            -   name: Test
                run: |
                    docker compose -f debian/docker-compose.yml up -d
                    env TRACE=true ./debian/scripts/test
                    docker compose -f debian/docker-compose.yml logs

    release:
        needs:
            - "build-deb"
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            -   name: Download deb
                uses: actions/download-artifact@v3
                with:
                    name: deb

            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        *.deb
