name: Deploy for amd64 / Debian

on:
    push:
        branches: [ "main" ]
        tags: [ "*" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-deb:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    -   distro_base: "debian"
                        distro: "bullseye"
                    -   distro_base: "debian"
                        distro: "bookworm"

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Generate params if needed
                run: ./debian/scripts/gen-params | tee ./debian/scripts/params.bash

            -   name: Check package version
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    set -x
                    source ./debian/scripts/env.bash
                    [ "v$PKG_VERSION" = "$GITHUB_REF_NAME" ]

            -   name: Restore cache
                uses: actions/cache/restore@v3
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ env.CACHE_KEY_PREFIX }}-${{ github.sha }}
                    restore-keys: |
                        ${{ env.CACHE_KEY_PREFIX }}-${{ github.sha }}
                        ${{ env.CACHE_KEY_PREFIX }}-
                env:
                    CACHE_KEY_PREFIX: buildx-cache-${{ matrix.distro_base }}-${{ matrix.distro }}-${{ hashFiles('./debian/scripts/env.bash') }}

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
                with:
                    install: true

            -   name: Build deb
                uses: docker/build-push-action@v4
                with:
                    context: ./debian
                    load: true
                    target: debcontainer
                    build-args: |
                        DISTRO_BASE=${{ matrix.distro_base }}
                        DISTRO=${{ matrix.distro }}
                    tags: ghcr.io/mizunashi-mana/firefish-dist-pkg/debian-debcontainer
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache

            -   name: Copy deb
                run: |
                    docker create --name deb ghcr.io/mizunashi-mana/firefish-dist-pkg/debian-debcontainer
                    docker cp deb:/workdir/dest ./dest
                    docker rm deb
                    for file in $(find ./dest -type f); do
                        mv "$file" "$(dirname "$file")/${DEST_PREFIX}_$(basename "$file")"
                    done
                env:
                    DEST_PREFIX: ${{ matrix.distro_base }}-${{ matrix.distro }}

            -   name: Archive deb artifact
                uses: actions/upload-artifact@v3
                with:
                    name: deb-${{ matrix.distro_base }}-${{ matrix.distro }}
                    retention-days: 1
                    path: |
                        ./dest/*.deb

            -   name: Build compose images
                uses: docker/bake-action@v3
                with:
                    workdir: ./debian
                    files: ./docker-compose.yml
                    load: true
                    set: |
                        *.cache-from=type=local,src=/tmp/.buildx-cache
                        *.cache-to=type=local,dest=/tmp/.buildx-cache
                        *.args.DISTRO_BASE=${{ matrix.distro_base }}
                        *.args.DISTRO=${{ matrix.distro }}

            -   name: Pull compose images
                run: |
                    docker compose -f debian/docker-compose.yml pull postgres redis

            -   name: Test
                run: |
                    docker compose -f debian/docker-compose.yml up -d
                    env TRACE=true ./debian/scripts/test
                    docker compose -f debian/docker-compose.yml logs

            -   name: Save cache
                if: startsWith(github.ref, 'refs/heads/')
                uses: actions/cache/save@v3
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ env.CACHE_KEY_PREFIX }}-${{ github.sha }}
                env:
                    CACHE_KEY_PREFIX: buildx-cache-${{ matrix.distro_base }}-${{ matrix.distro }}-${{ hashFiles('./debian/scripts/env.bash') }}

    release:
        needs:
            - "build-deb"
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            -   name: Download deb for Debian bullseye
                uses: actions/download-artifact@v3
                with:
                    name: deb-debian-bullseye

            -   name: Download deb for Debian bookworm
                uses: actions/download-artifact@v3
                with:
                    name: deb-debian-bookworm

            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        *.deb
