name: Deploy for amd64 / Debian bookworm

on:
    push:
        branches: [ "main" ]
        tags: [ "*" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-deb:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Generate params if needed
                if: startsWith(github.ref, 'refs/tags/')
                run: ./debian/scripts/gen-params

            -   name: Check package version
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    source ./debian/scripts/env.bash
                    [ "$PKG_VERSION" = "$GITHUB_REF_NAME" ]

            -   name: Set up Docker Buildx
                id: buildx
                uses: docker/setup-buildx-action@v2

            -   name: Cache Docker layers
                uses: actions/cache@v3
                with:
                    path: /tmp/.buildx-cache
                    key: buildx-cache-${{ hashFiles('./debian/scripts/env.bash') }}-${{ github.sha }}
                    restore-keys: |
                        buildx-cache-${{ hashFiles('./debian/scripts/env.bash') }}-${{ github.sha }}
                        buildx-cache-${{ hashFiles('./debian/scripts/env.bash') }}
                        buildx-cache-

            -   name: Build deb
                uses: docker/build-push-action@v4
                with:
                    context: ./debian
                    push: false
                    load: true
                    target: builder
                    tags: mizunashi-mana/firefish-dist-pkg/debian-builder
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache

            -   name: Copy deb
                uses: shrink/actions-docker-extract@v2
                id: build_deb_extract
                with:
                    image: mizunashi-mana/firefish-dist-pkg/debian-builder
                    path: /workdir/dest/.

            -   name: Archive deb artifact
                uses: actions/upload-artifact@v3
                with:
                    name: deb
                    retention-days: 1
                    path: |
                        ${{ steps.build_deb_extract.outputs.destination }}/*.deb

            -   name: Build runner image
                uses: docker/build-push-action@v4
                with:
                    context: ./debian
                    push: false
                    load: true
                    target: runner
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache

            -   name: Pull compose images
                run: |
                    docker compose -f debian/docker-compose.yml pull

            -   name: Build compose images
                uses: docker/bake-action@v3
                with:
                    files: ./debian/docker-compose.yml
                    load: true
                    set: |
                        *.cache-from=type=local,src=/tmp/.buildx-cache
                        *.cache-to=type=local,dest=/tmp/.buildx-cache

            -   name: Test
                run: |
                    docker compose -f debian/docker-compose.yml up -d
                    env TRACE=true ./debian/scripts/test

    release:
        needs:
            - "build-deb"
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            -   name: Download deb
                uses: actions/download-artifact@v3
                with:
                    name: deb

            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        *.deb
