name: Deploy for amd64 / Debian bookworm

on:
    push:
        branches: [ "main" ]
        tags: [ "*" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-deb:
        runs-on: ubuntu-latest
        container:
            image: debian:bookworm

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Cache nodejs
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.npm
                    key: nodejs-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                    restore-keys: |
                        nodejs-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                        nodejs-${{ runner.os }}-${{ runner.arch }}-

            -   name: Cache rust
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.rustup
                        ~/.cargo
                        ~/.local
                        ~/.cache
                    key: rust-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}
                    restore-keys: |
                        rust-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}
                        rust-${{ runner.os }}-${{ runner.arch }}-

            -   name: Install dependencies
                run: env TRACE=true ./debian/scripts/install-deps

            -   name: Build
                run: env TRACE=true ./debian/scripts/build-source

            -   name: Build deb
                run: env TRACE=true ./debian/scripts/build-deb

            -   name: Archive deb artifact
                if: startsWith(github.ref, 'refs/tags/')
                uses: actions/upload-artifact@v3
                with:
                    name: deb
                    retention-days: 3
                    path: |
                        ./debian/install/*.deb

            -   name: Test
                run: env TRACE=true ./debian/scripts/test

    release:
        needs:
            - "build-deb"
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            -   name: Download deb
                uses: actions/download-artifact@v3
                with:
                    name: deb

            -   name: Release
                uses: softprops/action-gh-release@v1
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    files: |
                        *.deb
