name: Deploy for amd64 / Debian bookworm

on:
    push:
        branches: [ "main" ]
        tags: [ "*" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-deb:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Generate params if needed
                if: startsWith(github.ref, 'refs/tags/')
                run: ./debian/scripts/gen-params

            -   name: Check package version
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    source ./debian/scripts/env.bash
                    [ "$PKG_VERSION" = "$GITHUB_REF_NAME" ]

            -   name: Cache Docker layers
                uses: actions/cache@v3
                with:
                    path: /tmp/.buildx-cache
                    key: buildx-cache-${{ hashFiles('./debian/scripts/env.bash') }}-${{ github.sha }}
                    restore-keys: |
                        buildx-cache-${{ hashFiles('./debian/scripts/env.bash') }}-${{ github.sha }}
                        buildx-cache-${{ hashFiles('./debian/scripts/env.bash') }}-

            -   name: Boot-up Local Docker Registry
                run: |
                    docker run --detach --publish 5000:5000 \
                        --restart=always \
                        --name registry \
                        --volume /tmp/docker-registry:/var/lib/registry \
                        registry:2

            -   name: Wait for Docker Registry
                run: npx wait-on tcp:5000

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
                with:
                    install: true
                    driver-opts: network=host

            -   name: Build deb
                uses: docker/build-push-action@v4
                with:
                    context: ./debian
                    push: true
                    target: builder
                    tags: localhost:5000/firefish-dist-pkg/debian-builder
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache

            -   name: Copy deb
                run: |
                    docker create --name deb-container localhost:5000/firefish-dist-pkg/debian-builder
                    docker cp deb-container:/workdir/dest ./dest
                    docker rm deb-container
                    ls ./dest

            -   name: Archive deb artifact
                uses: actions/upload-artifact@v3
                with:
                    name: deb
                    retention-days: 1
                    path: |
                        ./dest/*.deb

            -   name: Build runner image
                uses: docker/build-push-action@v4
                with:
                    context: ./debian
                    push: true
                    target: runner
                    tags: localhost:5000/firefish-dist-pkg/debian-runner
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache

            -   name: Pull compose images
                run: |
                    docker pull localhost:5000/firefish-dist-pkg/debian-runner
                    docker compose -f debian/docker-compose.yml pull

            -   name: Build compose images
                uses: docker/bake-action@v3
                with:
                    workdir: ./debian
                    files: ./docker-compose.yml
                    load: true
                    set: |
                        *.cache-from=type=local,src=/tmp/.buildx-cache
                        *.cache-to=type=local,dest=/tmp/.buildx-cache

            -   name: Test
                run: |
                    docker compose -f debian/docker-compose.yml up -d
                    env TRACE=true ./debian/scripts/test

    release:
        needs:
            - "build-deb"
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            -   name: Download deb
                uses: actions/download-artifact@v3
                with:
                    name: deb

            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        *.deb
